[08-Aug-23 19:39:10 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:39:10 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:39:10 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:39:10 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:39:10 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:10 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:39:10 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:10 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:39:10 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:10 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:39:10 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:39:29 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:39:30 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:39:30 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:39:30 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:39:30 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:30 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:39:30 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:30 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:39:30 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:30 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:39:30 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:39:48 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:39:48 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:39:48 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:39:48 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:39:48 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:48 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:39:48 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:48 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:39:48 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:39:48 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:39:48 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:39:51 - INFO - font_manager.py:1547 - _load_fontmanager()]  generated new fontManager
[08-Aug-23 19:40:31 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:40:31 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:40:32 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:40:32 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:40:32 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:40:32 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:40:32 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:40:32 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:40:32 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:40:32 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:40:32 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:40:39 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:40:39 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:40:39 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:40:39 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:40:39 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:40:41 - CRITICAL - init.py:142 - <module>()]  update expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 122, in <module>
    visualizationBuffers.update((poses[i].X(), poses[i].Y()), poses[i].Z())
TypeError: update expected at most 1 argument, got 2
[08-Aug-23 19:40:41 - INFO - init.py:143 - <module>()]  Shutting down
[08-Aug-23 19:41:08 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:41:09 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:41:09 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:41:09 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:41:09 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:41:09 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:41:09 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:41:09 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:41:09 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:41:09 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:41:09 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:41:16 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:41:16 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:41:16 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:41:16 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:41:16 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:41:18 - CRITICAL - init.py:142 - <module>()]  cannot convert dictionary update sequence element #0 to a sequence
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 122, in <module>
    visualizationBuffers.update((poses[i].X(), poses[i].Y(), poses[i].Z()))
TypeError: cannot convert dictionary update sequence element #0 to a sequence
[08-Aug-23 19:41:18 - INFO - init.py:143 - <module>()]  Shutting down
[08-Aug-23 19:42:12 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:42:12 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:42:12 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:42:12 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:42:12 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:42:12 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:42:12 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:42:12 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:42:12 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:42:12 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:42:12 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:42:19 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:42:19 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:42:19 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:42:19 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:42:19 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:42:21 - CRITICAL - init.py:143 - <module>()]  cannot convert dictionary update sequence element #0 to a sequence
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 123, in <module>
    visualizationBuffers.update((poses[i].X(), poses[i].Y(), poses[i].Z()))
TypeError: cannot convert dictionary update sequence element #0 to a sequence
[08-Aug-23 19:42:21 - INFO - init.py:144 - <module>()]  Shutting down
[08-Aug-23 19:42:46 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:42:46 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:42:46 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:42:46 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:42:46 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:42:46 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:42:46 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:42:46 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:42:46 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:42:46 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:42:46 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:42:53 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:42:53 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:42:53 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:42:53 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:42:53 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:42:55 - CRITICAL - init.py:143 - <module>()]  cannot convert dictionary update sequence element #0 to a sequence
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 123, in <module>
    visualizationBuffers.update((poses[i].X(), poses[i].Y(), poses[i].Z()))
TypeError: cannot convert dictionary update sequence element #0 to a sequence
[08-Aug-23 19:42:55 - INFO - init.py:144 - <module>()]  Shutting down
[08-Aug-23 19:44:09 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:44:09 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:44:09 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:44:09 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:44:09 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:44:09 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:44:09 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:44:09 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:44:09 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:44:09 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:44:09 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:44:16 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:44:16 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:44:16 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:44:16 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:44:16 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:44:21 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:44:28 - WARNING - InterfaceTest.py:44 - disconnect()]  Client disconnected
[08-Aug-23 19:45:31 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:46:10 - INFO - camera.py:129 - setCalibration()]  Calibration set for platform-fc880000.usb-usb-0:1:1.0-video-index0, using [[1.12889265e+03 0.00000000e+00 6.56741922e+02]
 [0.00000000e+00 1.12650013e+03 3.81503082e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[-4.92645684e+00  1.89161897e+01  4.08592693e-02  1.13369820e-02
   9.27324866e+00 -5.02962119e+00  1.97458051e+01  7.77362400e+00
  -1.09613475e-02 -1.46723591e-03 -4.67705256e-02  1.49777416e-02
  -7.31860369e-02  1.52249295e-02]]
[08-Aug-23 19:46:10 - INFO - InterfaceTest.py:107 - import_calibration()]  Calibration sucessfully imported for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:46:13 - INFO - InterfaceTest.py:159 - toggle_pnp()]  PnP stopped
[08-Aug-23 19:46:15 - INFO - InterfaceTest.py:162 - toggle_pnp()]  PnP started
[08-Aug-23 19:46:46 - INFO - init.py:126 - <module>()]  Shutting down
[08-Aug-23 19:47:35 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:47:35 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:47:35 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:47:35 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:47:35 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:47:35 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:47:35 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:47:35 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:47:35 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:47:35 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:47:35 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:47:42 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:47:42 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:47:42 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:47:42 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:47:42 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:47:43 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:47:44 - CRITICAL - init.py:143 - <module>()]  'FigureCanvasGTK4Agg' object has no attribute 'tostringbgr'
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 123, in <module>
    visualizationBuffers[identifier].update((poses[i].X(), poses[i].Y(), poses[i].Z()))
  File "/home/orangepi/Desktop/wallEYE-main/WebInterface/ImageStreams.py", line 86, in update
    plot = np.frombuffer(self.fig.canvas.tostringbgr(), dtype=np.uint8)
AttributeError: 'FigureCanvasGTK4Agg' object has no attribute 'tostringbgr'
[08-Aug-23 19:47:44 - INFO - init.py:144 - <module>()]  Shutting down
[08-Aug-23 19:47:57 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:47:57 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:47:57 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:47:57 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:47:57 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:47:57 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:47:57 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:47:57 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:47:58 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:47:58 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:47:58 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:48:04 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:48:04 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:48:04 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:48:04 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:48:04 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:48:06 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:48:06 - CRITICAL - init.py:143 - <module>()]  'FigureCanvasGTK4Agg' object has no attribute 'tostring_bgr'
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 123, in <module>
    visualizationBuffers[identifier].update((poses[i].X(), poses[i].Y(), poses[i].Z()))
  File "/home/orangepi/Desktop/wallEYE-main/WebInterface/ImageStreams.py", line 86, in update
    plot = np.frombuffer(self.fig.canvas.tostring_bgr(), dtype=np.uint8)
AttributeError: 'FigureCanvasGTK4Agg' object has no attribute 'tostring_bgr'
[08-Aug-23 19:48:06 - INFO - init.py:144 - <module>()]  Shutting down
[08-Aug-23 19:48:57 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:48:57 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:48:57 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:48:57 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:48:57 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:48:57 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:48:57 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:48:57 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:48:57 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:48:57 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:48:57 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:49:04 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:49:04 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:49:04 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:49:04 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:49:04 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:49:06 - CRITICAL - init.py:143 - <module>()]  too many indices for array: array is 1-dimensional, but 3 were indexed
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 123, in <module>
    visualizationBuffers[identifier].update((poses[i].X(), poses[i].Y(), poses[i].Z()))
  File "/home/orangepi/Desktop/wallEYE-main/WebInterface/ImageStreams.py", line 86, in update
    plot = np.frombuffer(self.fig.canvas.tostring_rgb(), dtype=np.uint8)[:, :, ::-1]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
[08-Aug-23 19:49:06 - INFO - init.py:144 - <module>()]  Shutting down
[08-Aug-23 19:49:55 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:49:55 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:49:55 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:49:55 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:49:55 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:49:55 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:49:55 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:49:55 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:49:55 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:49:55 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:49:55 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:50:02 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:50:02 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:50:02 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:50:02 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:50:02 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:50:02 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:50:04 - CRITICAL - init.py:143 - <module>()]  cannot reshape array of size 2764800 into shape (480,640,3)
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 123, in <module>
    visualizationBuffers[identifier].update((poses[i].X(), poses[i].Y(), poses[i].Z()))
  File "/home/orangepi/Desktop/wallEYE-main/WebInterface/ImageStreams.py", line 87, in update
    img  = plot.reshape(self.fig.canvas.get_width_height()[::-1] + (3,))
ValueError: cannot reshape array of size 2764800 into shape (480,640,3)
[08-Aug-23 19:50:04 - INFO - init.py:144 - <module>()]  Shutting down
[08-Aug-23 19:50:23 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[08-Aug-23 19:50:23 - INFO - state.py:133 - setIP()]  Attempting to set static IP
[08-Aug-23 19:50:23 - INFO - state.py:136 - setIP()]  Static IP set: 10.27.67.10
[08-Aug-23 19:50:23 - INFO - camera.py:38 - __init__()]  Platform is linux
[08-Aug-23 19:50:23 - INFO - camera.py:52 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:50:23 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[08-Aug-23 19:50:24 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:50:24 - INFO - camera.py:98 - __init__()]  Config found!
[08-Aug-23 19:50:24 - ERROR - camera.py:152 - setResolution()]  Failed to set resolution to [800, 600] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[08-Aug-23 19:50:24 - INFO - camera.py:177 - setGain()]  Gain set to 1.0
[08-Aug-23 19:50:24 - INFO - camera.py:196 - setExposure()]  Exposure set to 7.0
[08-Aug-23 19:50:30 - INFO - init.py:41 - <module>()]  Web server ready
[08-Aug-23 19:50:30 - INFO - state.py:100 - makePublisher()]  Robot publisher created: 2767 - Walleye
[08-Aug-23 19:50:30 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[08-Aug-23 19:50:30 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[08-Aug-23 19:50:30 - INFO - init.py:51 - <module>()]  Starting main loop
[08-Aug-23 19:50:31 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:50:37 - WARNING - InterfaceTest.py:44 - disconnect()]  Client disconnected
[08-Aug-23 19:50:38 - INFO - InterfaceTest.py:39 - connect()]  Client connected
[08-Aug-23 19:50:46 - WARNING - InterfaceTest.py:44 - disconnect()]  Client disconnected
[09-Aug-23 15:58:30 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[09-Aug-23 15:58:32 - INFO - state.py:135 - setIP()]  Attempting to set static IP
[09-Aug-23 16:35:57 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[09-Aug-23 16:35:57 - INFO - state.py:137 - setIP()]  Attempting to set static IP
