[24-Aug-23 19:41:26 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:41:26 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:41:26 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:41:26 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:41:27 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:41:27 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:41:27 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:41:27 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:41:27 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:41:27 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:41:27 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:41:27 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:41:27 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:41:28 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:41:31 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:41:31 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:41:31 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:41:31 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:41:31 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:41:33 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:41:57 - WARNING - web_interface.py:47 - disconnect()]  Client disconnected
[24-Aug-23 19:41:57 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:41:58 - WARNING - web_interface.py:47 - disconnect()]  Client disconnected
[24-Aug-23 19:41:58 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:48:07 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:48:07 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:48:07 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:48:07 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:48:08 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:48:08 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:48:08 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:48:08 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:48:08 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:48:08 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:48:08 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:48:08 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:48:08 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:48:09 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:48:14 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:48:14 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:48:14 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:48:14 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:48:14 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:48:17 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:48:22 - WARNING - web_interface.py:47 - disconnect()]  Client disconnected
[24-Aug-23 19:48:22 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:48:25 - CRITICAL - init.py:157 - <module>()]  OpenCV(4.7.0) /io/opencv/modules/calib3d/src/solvepnp.cpp:838: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) || (npoints >= 3 && flags == SOLVEPNP_SQPNP) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'solvePnPGeneric'
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 120, in <module>
    poses, tags, ambig = poseEstimator.getPose(
  File "/home/orangepi/Desktop/wallEYE-main/Processing/Processing.py", line 24, in getPose
    return self.imagePose(images, K, D, self.tagLayout, self.arucoDetector)
  File "/home/orangepi/Desktop/wallEYE-main/Processing/Processing.py", line 125, in imagePose
    ret, rvec, tvec, reproj = cv2.solvePnPGeneric(np.asarray([tempc2, tempc1, tempc3, tempc4]), cornerLoc, K[imgIndex], D[imgIndex], flags = cv2.SOLVEPNP_IPPE_SQUARE)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/calib3d/src/solvepnp.cpp:838: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) || (npoints >= 3 && flags == SOLVEPNP_SQPNP) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'solvePnPGeneric'

[24-Aug-23 19:48:25 - INFO - init.py:158 - <module>()]  Shutting down
[24-Aug-23 19:48:27 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:48:27 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:48:27 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:48:27 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:48:27 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:48:27 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:48:27 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:48:27 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:48:27 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:48:27 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:48:27 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:48:27 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:48:27 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:48:28 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:48:31 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:48:31 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:48:31 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:48:31 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:48:31 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:48:36 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:50:29 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:50:29 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:50:29 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:50:29 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:50:30 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:50:30 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:50:30 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:50:30 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:50:30 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:50:30 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:50:30 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:50:30 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:50:30 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:50:31 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:50:35 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:50:35 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:50:35 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:50:35 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:50:35 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:50:36 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:50:36 - ERROR - server.py:439 - handle_request()]  post request handler error
Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.10/site-packages/engineio/server.py", line 430, in handle_request
    socket.handle_post_request(environ)
  File "/home/orangepi/.local/lib/python3.10/site-packages/engineio/socket.py", line 124, in handle_post_request
    p = payload.Payload(encoded_payload=body)
  File "/home/orangepi/.local/lib/python3.10/site-packages/engineio/payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "/home/orangepi/.local/lib/python3.10/site-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
[24-Aug-23 19:50:37 - CRITICAL - init.py:157 - <module>()]  OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'Rodrigues'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 120, in <module>
    poses, tags, ambig = poseEstimator.getPose(
  File "/home/orangepi/Desktop/wallEYE-main/Processing/Processing.py", line 24, in getPose
    return self.imagePose(images, K, D, self.tagLayout, self.arucoDetector)
  File "/home/orangepi/Desktop/wallEYE-main/Processing/Processing.py", line 157, in imagePose
    rotMat, _ = cv2.Rodrigues(rvecs)
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'Rodrigues'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

[24-Aug-23 19:50:37 - INFO - init.py:158 - <module>()]  Shutting down
[24-Aug-23 19:50:38 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:50:38 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:50:38 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:50:38 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:50:39 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:50:39 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:50:39 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:50:39 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:50:39 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:50:39 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:50:39 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:50:39 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:50:39 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:50:39 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:50:43 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:50:43 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:50:43 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:50:43 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:50:43 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:50:46 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:51:04 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:51:04 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:51:04 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:51:04 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:51:05 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:51:05 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:51:05 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:51:05 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:51:05 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:51:05 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:51:05 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:51:05 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:51:05 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:51:05 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:51:09 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:51:09 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:51:09 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:51:09 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:51:09 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:51:14 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:51:17 - CRITICAL - init.py:157 - <module>()]  OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'Rodrigues'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'
Traceback (most recent call last):
  File "/home/orangepi/Desktop/wallEYE-main/init.py", line 120, in <module>
    poses, tags, ambig = poseEstimator.getPose(
  File "/home/orangepi/Desktop/wallEYE-main/Processing/Processing.py", line 24, in getPose
    return self.imagePose(images, K, D, self.tagLayout, self.arucoDetector)
  File "/home/orangepi/Desktop/wallEYE-main/Processing/Processing.py", line 157, in imagePose
    rotMat, _ = cv2.Rodrigues(rvecs)
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'Rodrigues'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

[24-Aug-23 19:51:17 - INFO - init.py:158 - <module>()]  Shutting down
[24-Aug-23 19:51:18 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:51:18 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:51:18 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:51:18 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:51:19 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:51:19 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:51:19 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:51:19 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:51:19 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:51:19 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:51:19 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:51:19 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:51:19 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:51:19 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:51:23 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:51:23 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:51:23 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:51:23 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:51:23 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:51:23 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:52:09 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[24-Aug-23 19:52:09 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[24-Aug-23 19:52:09 - INFO - state.py:141 - setIP()]  Static IP set: 10.27.67.10
[24-Aug-23 19:52:09 - INFO - camera.py:21 - __init__()]  Platform is linux
[24-Aug-23 19:52:10 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:52:10 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (320, 240), (640, 480), (800, 600), (1280, 720), (1280, 960), (1600, 1200)]
[24-Aug-23 19:52:10 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:52:10 - INFO - camera.py:82 - __init__()]  Config found!
[24-Aug-23 19:52:10 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1600, 1200)CalData.json
[24-Aug-23 19:52:10 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[1.03592100e+03 0.00000000e+00 8.16027156e+02]
 [0.00000000e+00 9.49446252e+02 6.16439233e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.04960712 -0.11274606 -0.05482673 -0.01093117  0.08518365 -0.03518569
   0.05428022 -0.05727628  0.02503255 -0.03094144  0.05682528  0.04272835
   0.13798034 -0.04358925]]
[24-Aug-23 19:52:10 - INFO - camera.py:152 - setResolution()]  Resolution set to (1600, 1200) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[24-Aug-23 19:52:10 - INFO - camera.py:166 - setGain()]  Gain set to 37.0
[24-Aug-23 19:52:10 - INFO - camera.py:187 - setExposure()]  Exposure set to 58.0
[24-Aug-23 19:52:11 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[24-Aug-23 19:52:14 - INFO - init.py:44 - <module>()]  Web server ready
[24-Aug-23 19:52:14 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[24-Aug-23 19:52:14 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[24-Aug-23 19:52:14 - INFO - init.py:53 - <module>()]  Starting main loop
[24-Aug-23 19:52:14 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[24-Aug-23 19:52:18 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:52:31 - WARNING - web_interface.py:47 - disconnect()]  Client disconnected
[24-Aug-23 19:52:32 - INFO - web_interface.py:42 - connect()]  Client connected
[24-Aug-23 19:52:45 - WARNING - web_interface.py:47 - disconnect()]  Client disconnected
[24-Aug-23 19:52:45 - INFO - web_interface.py:42 - connect()]  Client connected
